### ISSUE TITLE
The ability to install a specific version of marzban

### ISSUE THREAD

**Issue by Kiya6955** [Gozargah/Marzban-scripts#17]
Hi
We need an ability to install a specific version of marzban without rolling back from the latest version.

**Comment by iamtheted** [comment]
Hi
I think the docker on previous versions of Marzban should be edited and each version should have its own version in image section instead of "latest" , I think it'll fix it but I have no idea if that's doable.

**Comment by DigneZzZ** [comment]
In release.

close it.
